use base64::{engine::general_purpose::STANDARD, Engine as _};
use windows::{
    core::PCWSTR,
    Win32::{
        Foundation::{HLOCAL, LocalFree},
        Security::Cryptography::{
            CryptProtectData, CryptUnprotectData, CRYPTPROTECT_UI_FORBIDDEN,
            CRYPT_INTEGER_BLOB,
        },
    },
};

const ENTROPY: &[u8] = b"Prismeter.DeepSeek.v1";

pub fn protect(value: &str) -> Result<String, String> {
    let input = blob(value.as_bytes());
    let entropy = blob(ENTROPY);
    let mut output = CRYPT_INTEGER_BLOB::default();
    unsafe {
        CryptProtectData(
            &input,
            PCWSTR::null(),
            Some(&entropy),
            None,
            None,
            CRYPTPROTECT_UI_FORBIDDEN,
            &mut output,
        )
        .map_err(|error| format!("Windows 无法加密账户凭据：{error}"))?;
        Ok(STANDARD.encode(copy_and_free(output)))
    }
}

pub fn unprotect(value: &str) -> Result<String, String> {
    let encrypted = STANDARD
        .decode(value)
        .map_err(|_| "账户凭据格式无效，请重新添加该账户。".to_string())?;
    let input = blob(&encrypted);
    let entropy = blob(ENTROPY);
    let mut output = CRYPT_INTEGER_BLOB::default();
    unsafe {
        CryptUnprotectData(
            &input,
            None,
            Some(&entropy),
            None,
            None,
            CRYPTPROTECT_UI_FORBIDDEN,
            &mut output,
        )
        .map_err(|error| format!("Windows 无法解密账户凭据：{error}"))?;
        String::from_utf8(copy_and_free(output))
            .map_err(|_| "账户凭据不是有效的 UTF-8 数据。".to_string())
    }
}

fn blob(bytes: &[u8]) -> CRYPT_INTEGER_BLOB {
    CRYPT_INTEGER_BLOB {
        cbData: bytes.len() as u32,
        pbData: bytes.as_ptr() as *mut u8,
    }
}

unsafe fn copy_and_free(output: CRYPT_INTEGER_BLOB) -> Vec<u8> {
    let bytes = if output.pbData.is_null() || output.cbData == 0 {
        Vec::new()
    } else {
        unsafe { std::slice::from_raw_parts(output.pbData, output.cbData as usize) }.to_vec()
    };
    if !output.pbData.is_null() {
        unsafe { LocalFree(Some(HLOCAL(output.pbData.cast()))) };
    }
    bytes
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn windows_dpapi_round_trip_preserves_unicode() {
        let plain = "中文凭据-0.8.11-🔐";
        let encrypted = protect(plain).expect("DPAPI encryption should succeed");
        assert_ne!(encrypted, plain);
        assert_eq!(unprotect(&encrypted).expect("DPAPI decryption should succeed"), plain);
    }

    #[test]
    fn invalid_base64_has_a_readable_error() {
        let error = unprotect("not a dpapi payload").unwrap_err();
        assert!(error.contains("格式无效"));
    }

    #[test]
    #[ignore = "requires a DPAPI fixture generated by the legacy C# bridge"]
    fn decrypts_legacy_csharp_fixture() {
        let encrypted = std::env::var("PRISMETER_LEGACY_DPAPI_FIXTURE")
            .expect("legacy fixture is required");
        let expected = std::env::var("PRISMETER_LEGACY_DPAPI_PLAIN")
            .expect("legacy plain text is required");
        assert_eq!(unprotect(&encrypted).expect("Rust should decrypt the C# fixture"), expected);
    }
}
